/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3c4a42",
        "surface-container-low": "#f0f4f8",
        "surface-container-high": "#e4e9ed",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d3e4fe",
        "on-primary": "#ffffff",
        "inverse-primary": "#8bd6b6",
        surface: "#f6fafe",
        secondary: "#505f76",
        "on-tertiary": "#ffffff",
        "on-surface": "#171c1f",
        "on-secondary-fixed-variant": "#38485d",
        "primary-fixed": "#a6f2d1",
        "on-primary-container": "#00422f",
        "surface-variant": "#dfe3e7",
        "outline-variant": "#bbcabf",
        "surface-tint": "#1b6b51",
        "on-primary-fixed": "#002116",
        "on-tertiary-fixed-variant": "#783200",
        "surface-container": "#eaeef2",
        "secondary-container": "#d0e1fb",
        "surface-container-highest": "#dfe3e7",
        "inverse-surface": "#2c3134",
        "on-secondary-fixed": "#0b1c30",
        "on-error": "#ffffff",
        "on-secondary-container": "#54647a",
        "surface-bright": "#f6fafe",
        "on-primary-fixed-variant": "#00513b",
        tertiary: "#9d4300",
        "on-tertiary-fixed": "#341100",
        "surface-dim": "#d6dade",
        "tertiary-container": "#ff7e2d",
        error: "#ba1a1a",
        "inverse-on-surface": "#edf1f5",
        primary: "#1b6b51",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#67b193",
        "tertiary-fixed": "#ffdbca",
        "on-tertiary-container": "#622700",
        "on-background": "#171c1f",
        "primary-fixed-dim": "#8bd6b6",
        "secondary-fixed-dim": "#b7c8e1",
        outline: "#6c7a71",
        "on-secondary": "#ffffff",
        background: "#f6fafe",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb690",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
      boxShadow: {
        soft: "0 12px 32px rgba(23, 28, 31, 0.08)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        pulsebar: {
          "0%": { width: "12%" },
          "100%": { width: "86%" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-400px 0" },
          "100%": { backgroundPosition: "400px 0" },
        },
        typing: {
          "0%, 60%, 100%": { transform: "translateY(0)", opacity: "0.45" },
          "30%": { transform: "translateY(-4px)", opacity: "1" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        pulsebar: "pulsebar 3s ease-out infinite alternate",
        shimmer: "shimmer 1.8s linear infinite",
      },
    },
  },
  plugins: [],
};